image: docker:20.10.7

stages:
  - build
  - package
  - build-image

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.7-dind

.package:
  image: maven:3.6-openjdk-15-slim
  stage: build
  script:
    - mvn package -am -pl $MODULE_NAME
  artifacts:
    paths:
      - ./$MODULE_NAME/target/*.jar

.build-image:
  stage: build-image
  script:
    - cd config-server
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $LATEST_IMAGE || true
    - docker build --cache-from $LATEST_IMAGE -t $LATEST_IMAGE .
    - docker push $LATEST_IMAGE


package-config-server:
  extends: .package
  variables:
    MODULE_NAME: config-server

build-config-server:
  extends: .build-image
  variables:
    MODULE_NAME: config-server
    LATEST_IMAGE: "$CI_REGISTRY_IMAGE/config-server:latest"
