version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  auth-server:
    build: auth-server
    restart: on-failure
    depends_on:
      - config-server
      -
  config-server:
    build: config-server

  gateway:
    build: gateway
    restart: on-failure
    depends_on:
      - config-server

  history-service:
    build: history
    restart: on-failure
    depends_on:
      - config-server

  products-service:
    build: products
    restart: on-failure
    depends_on:
      - config-server
      -
  rating-service:
    build: rating
    restart: on-failure
    depends_on:
      - config-server

  shop-service:
    build: shop
    restart: on-failure
    depends_on:
      - config-server

  users-service:
    build: users
    restart: on-failure
    depends_on:
      - config-server

volumes:
  data:
