version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    network_mode: host
    expose:
      - 5672
      - 15672
    labels:
      - "SERVICE_5672_NAME=rabbitmq"
      - "SERVICE_15672_IGNORE=true"

  consul:
    image: consul
    container_name: consul
    network_mode: host
    expose:
      - 8500
      - 8600/udp
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"

  registrator:
    image: gliderlabs/registrator
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    network_mode: host
    command: consul://localhost:8500

  postgres:
    image: postgres
    expose:
      - 5432
    network_mode: host
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    labels:
      - "SERVICE_NAME=postgres"

#
#  pgadmin:
#    image: dpage/pgadmin4
#    networks:
#      - default
#      - public
#    environment:
#      PGADMIN_DEFAULT_EMAIL: amseyhani@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS?}
#      PGADMIN_DISABLE_POSTFIX: "true"
#      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
#      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 50
#    deploy:
#      replicas: 1
#      labels:
#        - traefik.enable=true
#        - traefik.docker.network=idb-public
#        - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN?}`)
#        - traefik.http.routers.pgadmin.entrypoints=https
#        - traefik.http.routers.pgadmin.tls=true
#        - traefik.http.routers.pgadmin.tls.certresolver=lecf
#        - traefik.http.services.pgadmin.loadbalancer.server.port=80

volumes:
  data:
