version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      - "SERVICE_5672_NAME=rabbitmq"
      - "SERVICE_15672_IGNORE=true"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    labels:
      - "SERVICE_NAME=postgres"

#
#  pgadmin:
#    image: dpage/pgadmin4
#    networks:
#      - default
#      - public
#    environment:
#      PGADMIN_DEFAULT_EMAIL: amseyhani@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS?}
#      PGADMIN_DISABLE_POSTFIX: "true"
#      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
#      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 50
#    deploy:
#      replicas: 1
#      labels:
#        - traefik.enable=true
#        - traefik.docker.network=idb-public
#        - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN?}`)
#        - traefik.http.routers.pgadmin.entrypoints=https
#        - traefik.http.routers.pgadmin.tls=true
#        - traefik.http.routers.pgadmin.tls.certresolver=lecf
#        - traefik.http.services.pgadmin.loadbalancer.server.port=80

volumes:
  data:
