spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8083
          predicates:
            - Path=/users

management:
  endpoints:
    web:
      exposure:
        include: "*"
